POST http://localhost:8080/ HTTP/1.1
content-type: application/json

{
    "content": [
        {
            "timestamp": {{$timestamp}},
            "value": {{$randomInt 1 43}},
            "timeOffsetHours": {{$randomInt 1 43}},
            "pointId": "{{$guid}}",
            "sequence": {{$randomInt 1 43}},
            "project": "{{$guid}}",
            "res": "{{$guid}}",
            "quality": {{$randomInt 1 43}}
        },
        {
            "timestamp": {{$timestamp}},
            "value": {{$randomInt 1 43}},
            "timeOffsetHours": {{$randomInt 1 43}},
            "pointId": "{{$guid}}",
            "sequence": {{$randomInt 1 43}},
            "project": "{{$guid}}",
            "res": "{{$guid}}",
            "quality": {{$randomInt 1 43}}
        },
        {
            "timestamp": {{$timestamp}},
            "value": {{$randomInt 1 43}},
            "timeOffsetHours": {{$randomInt 1 43}},
            "pointId": "{{$guid}}",
            "sequence": {{$randomInt 1 43}},
            "project": "{{$guid}}",
            "res": "{{$guid}}",
            "quality": {{$randomInt 1 43}}
        }
    ],
    "file": "2023/10/11/{{$timestamp}}-{{$guid}}.parquet",
    "timeGenerated": {{$timestamp}},
    "id": "{{$guid}}"
}

###

POST http://localhost:8080/query?key=asd HTTP/1.1
content-type: application/json

{   
    "db":"adxdbhisv2",
    "csl":"OmyaData | count",
    "properties": {
            "Options":{ "queryconsistency": "strongconsistency"}
    }
}

###

POST https://ca-jsontoparquet-hisv2.livelyforest-5f9578c7.westeurope.azurecontainerapps.io/query?key=u5pvjtrozvx3c HTTP/1.1
content-type: application/json

{   
    "db":"adxdbhisv2",
    "csl":"OmyaData | count",
    "properties": {
            "Options":{ "queryconsistency": "strongconsistency"}
    }
}

###

GET http://localhost:8080/?key=123 HTTP/1.1
###
POST https://ca-jsontoparquet-rsgxnp2yzxobq.nicesea-49e4b167.westeurope.azurecontainerapps.io/?key=j3mhfhc4z4wng HTTP/1.1
content-type: application/json

{
    "content": [{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    },{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    },{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    }],
    "file": "2023/10/11/{{$timestamp}}-{{$guid}}.parquet",
    "timeGenerated": {{$timestamp}},
    "id": "{{$guid}}"
}