POST http://localhost:8080/ HTTP/1.1
content-type: application/json

{
    "content": [{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    },{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    },{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    }],
    "file": "2023/10/11/{{$timestamp}}-{{$guid}}.parquet",
    "timeGenerated": {{$timestamp}},
    "id": "{{$guid}}"
}

###

GET http://localhost:8080/ HTTP/1.1
###
POST https://ca-jsontoparquet-cnfg6rri5hakw.reddesert-df123858.westeurope.azurecontainerapps.io/
content-type: application/json

{
    "content": [{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    },{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    },{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    }],
    "file": "{{$timestamp}}-{{$guid}}",
    "timeGenerated": {{$timestamp}},
    "id": "{{$guid}}"
}