POST http://localhost:8080/ HTTP/1.1
content-type: application/json

{
    "content": [
        {
            "timestamp": {{$timestamp}},
            "value": {{$randomInt 1 43}},
            "timeOffsetHours": {{$randomInt 1 43}},
            "pointId": "{{$guid}}",
            "sequence": {{$randomInt 1 43}},
            "project": "{{$guid}}",
            "res": "{{$guid}}",
            "quality": {{$randomInt 1 43}}
        },
        {
            "timestamp": {{$timestamp}},
            "value": {{$randomInt 1 43}},
            "timeOffsetHours": {{$randomInt 1 43}},
            "pointId": "{{$guid}}",
            "sequence": {{$randomInt 1 43}},
            "project": "{{$guid}}",
            "res": "{{$guid}}",
            "quality": {{$randomInt 1 43}}
        },
        {
            "timestamp": {{$timestamp}},
            "value": {{$randomInt 1 43}},
            "timeOffsetHours": {{$randomInt 1 43}},
            "pointId": "{{$guid}}",
            "sequence": {{$randomInt 1 43}},
            "project": "{{$guid}}",
            "res": "{{$guid}}",
            "quality": {{$randomInt 1 43}}
        }
    ],
    "file": "2023/10/11/{{$timestamp}}-{{$guid}}.parquet",
    "timeGenerated": {{$timestamp}},
    "id": "{{$guid}}"
}

###

GET http://localhost:8080/?key=123 HTTP/1.1
###
POST https://cs-jsontoparquet-3b3rkdfzwqij4.wonderfulsea-1fb27218.westeurope.azurecontainerapps.io/ HTTP/1.1
content-type: application/json

{
    "content": [{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    },{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    },{
        "timestamp": {{$timestamp}},
        "value": {{$randomInt 1 43}}
    }],
    "fileXXXXX": "2023/10/11/{{$timestamp}}-{{$guid}}",
    "timeGenerated": {{$timestamp}},
    "id": "{{$guid}}"
}