name: Trigger auto deployment for ca-jsontoparquet-qmh6n6ngd4pj4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/ca-jsontoparquet-qmh6n6ngd4pj4-AutoDeployTrigger-c0e6525a-05eb-4acb-ac29-890921b8064a.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAJSONTOPARQUETQMH6N6NGD4PJ4_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src 
          registryUrl: anboparjscrdemo2.azurecr.io
          registryUsername: ${{ secrets.CAJSONTOPARQUETQMH6N6NGD4PJ4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAJSONTOPARQUETQMH6N6NGD4PJ4_REGISTRY_PASSWORD }}
          containerAppName: ca-jsontoparquet-qmh6n6ngd4pj4
          resourceGroup: anbo-parjs-demo-demo2
          imageToBuild: anboparjscrdemo2.azurecr.io/js2par:${{ github.sha }}
          dockerfilePath: Dockerfile

     

